services:
  frontend:
    image: sys74/student-frontend:latest
    container_name: frontend_container
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: sys74/student-backend:latest
    container_name: backend_container
    restart: unless-stopped
    ports:
      - "8000:8000"

  valkey:
    image: valkey/valkey:8-alpine
    container_name: valkey_container
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - valkey-data:/data
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local

  valkey-data:
