import z from "zod";
import { createIdFactoryFromIdSchema, idSchema } from "../id-factory";
import type { CollectionConfig } from "../../modules/mongodb/collection";
import type { TableConfig } from "../../modules/postgres/table";


export const StudentIdSchema = idSchema({ brand: "StudentId", prefix: "s_" });
export type StudentId = z.infer<typeof StudentIdSchema>;
export const createStudentId = createIdFactoryFromIdSchema(StudentIdSchema);

export const StudentGenderSchema = z.enum(["male", "female"])
export type StudentGender = z.infer<typeof StudentGenderSchema>

export const StudentSchema = z.object({
  _id: StudentIdSchema,
  admissionNumber: z.number(), // autogenerated
  name: z.string().max(120),
  course: z.string().max(120),
  year: z.string(),
  dob: z.iso.date(),
  email: z.email(),
  phone: z.string(),
  gender: StudentGenderSchema.optional(),
  address: z.string().optional(),
  profileImageUrl: z.url().optional()
})

export type Student = z.infer<typeof StudentSchema>

export const StudentCollectionConfig: CollectionConfig<Student> = {
  name: "students",
  indices: [],
  primaryKey: "_id",
  schema: StudentSchema,
  schemaVersion: 1,
};

export const StudentTableConfig: TableConfig<Student> = {
  name: "students",
  primaryKey: "_id",
  schema: StudentSchema,
};


